### ISSUE TITLE
Command-line completion mis-behaving?

### ISSUE THREAD

**Issue by atsalolikhin-spokeo** [AnthonyBloomer/nrql-simple#10]
Hello! I'm just trying nrql-cli because I thought the command line completion might be handy. However, it does not seem to be working.

For example, here I am getting suggestions that have nothing to do with the EMR integration:

```
[~/nrql-cli] [nrql-cli] $ nrql
Welcome to your data, let's get querying...
> from ElasticMapReduceInstanceSample select 
                                              IntegrationError
                                              is
                                              Transaction
                                              begin
                                              DSSTimeout
                                              where
                                              IntegrationError
                                              PaymentMetric
```

Compare that to the web UI:

![image](https://user-images.githubusercontent.com/66701226/93366618-46383a80-f800-11ea-8041-e0861d2e53fd.png)

**Comment by atsalolikhin-spokeo** [comment]
I'm using nrql-cli version 1.0.3:

```
[~/nrql-cli] [nrql-cli] $ pip freeze | grep nrql-cli
nrql-cli==1.0.3
[~/nrql-cli] [nrql-cli] $
```

**Comment by AnthonyBloomer** [comment]
Hi @atsalolikhin-spokeo, 

Thank you for creating this issue. 

I discovered this issue recently. This is due to how I was getting the event keyset:

```python
event_types_query = "show event types since 1 week ago"
keyset_query = "select keyset() from %s since 1 week ago"
events = nrql.query(event_types_query)
events = events["results"][0]["eventTypes"]
k = nrql.query(keyset_query % ", ".join(event for event in events))
words = list(set(reserved_words + events + k["results"][0]["allKeys"]))
```

The keyset query doesn't work now because default event types can't be mixed with custom data.

```
(env) abloomer@C02XHDU0JG5J:~/nrql-cli$ python -m nrql --v
⠏ Loading...['ApplicationAgentContext', 'IntegrationError', 'IntegrationProviderReport', 'JavaScriptError', 'Metric', 'NrAuditEvent', 'NrConsumption', 'NrDailyUsage', 'NrMTDConsumption', 'NrUsage', 'PageView', 'PageViewTiming', 'Public_APICall', 'SyntheticCheck', 'SyntheticRequest', 'SyntheticsPrivateLocationStatus', 'Transaction']
select keyset() from ApplicationAgentContext, IntegrationError, IntegrationProviderReport, JavaScriptError, Metric, PageView, PageViewTiming, Public_APICall, SyntheticCheck, SyntheticRequest, SyntheticsPrivateLocationStatus, Transaction since 1 week ago
⠇ Loading...{'error': 'Global event types cannot be mixed with account data'}
Traceback (most recent call last):
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/abloomer/nrql-cli/nrql/__main__.py", line 3, in <module>
    main()
  File "/Users/abloomer/nrql-cli/nrql/cli.py", line 75, in main
    wordlist = load_or_generate()
  File "/Users/abloomer/nrql-cli/nrql/utils.py", line 104, in load_or_generate
    word_list = generate_word_list()
  File "/Users/abloomer/nrql-cli/nrql/utils.py", line 92, in generate_word_list
    words = list(set(reserved_words + events + k["results"][0]["allKeys"]))
KeyError: 'results'
```

I removed that functionality until I can think of a better way of implementing it.

**Comment by atsalolikhin-spokeo** [comment]
> I removed that functionality until I can think of a better way of implementing it.

Understood.  Is it a lot of work to push out a patch release with the fix for the noise, please?  :)   One I could pull in via `pip install --upgrade nrql-cli` ?
